[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ProfileScript
)

$ErrorActionPreference = 'Stop'
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) (
    "pbvp-phase6-profile-$([Guid]::NewGuid().ToString('N'))")
$profiles = Join-Path $temporaryRoot 'profiles'
$source = Join-Path $profiles 'Source'
$mods = Join-Path $temporaryRoot 'mods'
[IO.Directory]::CreateDirectory((Join-Path $source 'saves')) | Out-Null
[IO.Directory]::CreateDirectory($mods) | Out-Null

$enabledMods = @(
    'Pip-Boy Video Player - Phase 1 Save Guard',
    'Pip-Boy Video Player - Dev',
    'Pip-Boy Video Player - Catalog Test',
    'Pip-Boy Video Player - Long Playback Test'
)
$disabledMods = @(
    'Pip-Boy Video Player - Playback Test',
    'Pip-Boy Video Player - Media Test',
    'Pip-Boy Video Player - Audio Test'
)
foreach ($modName in @($enabledMods + $disabledMods)) {
    [IO.Directory]::CreateDirectory((Join-Path $mods $modName)) | Out-Null
}
[IO.File]::WriteAllLines(
    (Join-Path $source 'modlist.txt'),
    @(
        '# This file was automatically generated by Mod Organizer.',
        '+Existing Mod',
        '-Pip-Boy Video Player - Dev',
        '+Pip-Boy Video Player - Audio Test'),
    [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText(
    (Join-Path $source 'fallout.ini'),
    '[Display]',
    [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText(
    (Join-Path $temporaryRoot 'ModOrganizer.ini'),
    "selected_profile=@ByteArray(Source)`n",
    [Text.UTF8Encoding]::new($false))

try {
    & $ProfileScript `
        -InstanceRoot $temporaryRoot `
        -SourceProfile 'Source' `
        -TargetProfile 'Hardening' `
        -SelectProfile
    & $ProfileScript `
        -InstanceRoot $temporaryRoot `
        -SourceProfile 'Source' `
        -TargetProfile 'Hardening' `
        -VerifyOnly

    $target = Join-Path $profiles 'Hardening'
    $modList = @(Get-Content -LiteralPath (Join-Path $target 'modlist.txt'))
    foreach ($modName in $enabledMods) {
        if (@($modList | Where-Object { $_ -eq "+$modName" }).Count -ne 1) {
            throw "The generated profile did not enable: $modName"
        }
    }
    foreach ($modName in $disabledMods) {
        if (@($modList | Where-Object { $_ -eq "-$modName" }).Count -ne 1) {
            throw "The generated profile did not disable: $modName"
        }
    }
    if (@($modList | Where-Object { $_ -eq '+Existing Mod' }).Count -ne 1 -or
        -not (Test-Path -LiteralPath (Join-Path $target 'fallout.ini'))) {
        throw 'The generated profile did not preserve its source files and unrelated mods.'
    }
    if ([IO.File]::ReadAllText((Join-Path $temporaryRoot 'ModOrganizer.ini')) -notmatch
        '(?m)^selected_profile=@ByteArray\(Hardening\)$') {
        throw 'The generated profile was not selected.'
    }

    $save = Join-Path $target 'saves\must-remain.fos'
    [IO.File]::WriteAllText($save, 'test save', [Text.UTF8Encoding]::new($false))
    $refused = $false
    try {
        & $ProfileScript `
            -InstanceRoot $temporaryRoot `
            -SourceProfile 'Source' `
            -TargetProfile 'Hardening'
    } catch {
        $refused = $true
    }
    if (-not $refused -or -not (Test-Path -LiteralPath $save)) {
        throw 'The Phase 6 profile script did not preserve and refuse existing save data.'
    }
    Write-Host 'Phase 6 profile tests passed.'
} finally {
    if ((Test-Path -LiteralPath $temporaryRoot) -and
        [IO.Path]::GetFileName($temporaryRoot) -like 'pbvp-phase6-profile-*' -and
        (Split-Path -Parent $temporaryRoot) -eq [IO.Path]::GetTempPath().TrimEnd('\')) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
    }
}
