[CmdletBinding()]
param([Parameter(Mandatory)][string]$ProfileScript)

$ErrorActionPreference = 'Stop'
$script = (Resolve-Path -LiteralPath $ProfileScript).Path
$tempRoot = [IO.Path]::GetFullPath(
    [IO.Path]::Combine([IO.Path]::GetTempPath(), "pbvp-profile-test-$([Guid]::NewGuid().ToString('N'))"))
$profiles = Join-Path $tempRoot 'profiles'
[IO.Directory]::CreateDirectory($profiles) | Out-Null
$mods = Join-Path $tempRoot 'mods'
[IO.Directory]::CreateDirectory($mods) | Out-Null

function New-SourceProfile {
    param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][string]$ModList)
    $profile = Join-Path $profiles $Name
    [IO.Directory]::CreateDirectory($profile) | Out-Null
    [IO.File]::WriteAllText((Join-Path $profile 'modlist.txt'), $ModList)
    [IO.File]::WriteAllText((Join-Path $profile 'fallout.ini'), '[General]')
    [IO.File]::WriteAllText((Join-Path $profile 'falloutprefs.ini'), '')
    $saves = Join-Path $profile 'saves'
    [IO.Directory]::CreateDirectory($saves) | Out-Null
    [IO.File]::WriteAllText((Join-Path $saves 'private.fos'), 'fixture')
}

try {
    foreach ($provider in @('Stewie_Tweaks-VNV_INI', 'Stewie_Tweaks-VNV_Extended_INI')) {
        $providerDirectory = Join-Path $mods "$provider\nvse\plugins"
        [IO.Directory]::CreateDirectory($providerDirectory) | Out-Null
        [IO.File]::WriteAllText(
            (Join-Path $providerDirectory 'nvse_stewie_tweaks.ini'),
            "[INI]`nbMultiINISupport = 1")
    }

    New-SourceProfile -Name 'Viva New Vegas' -ModList (
        "-Base separator`n+Base Fixes`n+Stewie_Tweaks-VNV_INI`n" +
        "-Stewie_Tweaks-VNV_Extended_INI`n+Stewie Tweaks")
    New-SourceProfile -Name 'Viva New Vegas Extended' -ModList (
        "# This file was automatically generated by Mod Organizer.`n" +
        "+Pip-Boy UI Tweaks - INI`n+Pip-Boy UI Tweaks`n" +
        "+Clean Vanilla Hud`n+Vanilla UI Plus (New Vegas)`n+Extended Fixes`n" +
        "+Stewie_Tweaks-VNV_Extended_INI`n-Stewie_Tweaks-VNV_INI`n+Stewie Tweaks")
    [IO.File]::WriteAllText(
        (Join-Path $profiles 'Viva New Vegas Extended\falloutprefs.ini'),
        "iSize W=1920`niSize H=1080`nbFull Screen=1")

    & $script -InstanceRoot $tempRoot -Confirm:$false
    & $script -InstanceRoot $tempRoot -VerifyOnly

    $guardName = 'Pip-Boy Video Player - Phase 1 Save Guard'
    $guardIni = Join-Path $mods (
        "$guardName\NVSE\Plugins\Tweaks\INIs\PipBoyVideoPlayerPhase1.ini")
    if (-not (Test-Path -LiteralPath $guardIni -PathType Leaf)) {
        throw 'The setup did not create the Phase 1 save guard mod.'
    }
    $guardText = [IO.File]::ReadAllText($guardIni)
    foreach ($expected in @(
            'bImprovedAutoSave = 0',
            'bSaveOnExitGame = 0',
            'iAutoSaveTimer = 0')) {
        if ($guardText -notmatch [Regex]::Escape($expected)) {
            throw "The save guard is missing '$expected'."
        }
    }

    foreach ($target in @(
            'PBVP Phase 1 Base',
            'PBVP Phase 1 VUI Plus',
            'PBVP Phase 1 Extended',
            'PBVP Phase 1 Extended No Pip-Boy Tweaks')) {
        if (Test-Path -LiteralPath (Join-Path $profiles "$target\saves")) {
            throw "The setup copied saves into $target."
        }
        $targetModList = @(Get-Content -LiteralPath (
            Join-Path $profiles "$target\modlist.txt"))
        if (@($targetModList | Where-Object { $_ -eq "+$guardName" }).Count -ne 1) {
            throw "The save guard is not enabled exactly once in $target."
        }
        [IO.Directory]::CreateDirectory((Join-Path $profiles "$target\saves")) | Out-Null
    }
    & $script -InstanceRoot $tempRoot -VerifyOnly

    $blockedSave = Join-Path $profiles 'PBVP Phase 1 Base\saves\blocked.fos'
    [IO.File]::WriteAllText($blockedSave, 'fixture')
    $saveDataRefused = $false
    try {
        & $script -InstanceRoot $tempRoot -VerifyOnly
    } catch {
        if ($_.Exception.Message -notmatch 'contains save data') { throw }
        $saveDataRefused = $true
    } finally {
        Remove-Item -LiteralPath $blockedSave -Force
    }
    if (-not $saveDataRefused) {
        throw 'Profile verification accepted actual save data.'
    }

    $refused = $false
    try {
        & $script -InstanceRoot $tempRoot -Confirm:$false
    } catch {
        if ($_.Exception.Message -notmatch 'Refusing to replace') {
            throw
        }
        $refused = $true
    }
    if (-not $refused) {
        throw 'The setup replaced existing test profiles.'
    }

    $vuiTarget = [IO.Path]::GetFullPath(
        (Join-Path $profiles 'PBVP Phase 1 VUI Plus'))
    if (-not $vuiTarget.StartsWith(
            [IO.Path]::GetFullPath($profiles) + [IO.Path]::DirectorySeparatorChar,
            [StringComparison]::OrdinalIgnoreCase)) {
        throw 'The VUI Plus fixture escaped the temporary profiles directory.'
    }
    Remove-Item -LiteralPath $vuiTarget -Recurse -Force
    & $script -InstanceRoot $tempRoot -CreateMissing -Confirm:$false
    & $script -InstanceRoot $tempRoot -VerifyOnly

    foreach ($target in @(
            'PBVP Phase 1 Base',
            'PBVP Phase 1 VUI Plus',
            'PBVP Phase 1 Extended',
            'PBVP Phase 1 Extended No Pip-Boy Tweaks')) {
        $targetModList = Join-Path $profiles "$target\modlist.txt"
        $lines = [Collections.Generic.List[string]]::new()
        foreach ($line in Get-Content -LiteralPath $targetModList) {
            if ($line -ne "+$guardName") { $lines.Add($line) }
        }
        [IO.File]::WriteAllLines($targetModList, $lines)
    }
    Remove-Item -LiteralPath (Join-Path $mods $guardName) -Recurse -Force
    & $script -InstanceRoot $tempRoot -InstallSaveGuard -Confirm:$false
    & $script -InstanceRoot $tempRoot -VerifyOnly

    $vuiList = @(Get-Content -LiteralPath (
        Join-Path $profiles 'PBVP Phase 1 VUI Plus\modlist.txt'))
    if ($vuiList -contains '+Clean Vanilla Hud' -or
        $vuiList -contains '+Pip-Boy UI Tweaks' -or
        $vuiList -contains '+Pip-Boy UI Tweaks - INI' -or
        @($vuiList | Where-Object {
            $_ -eq '+Vanilla UI Plus (New Vegas)'
        }).Count -ne 1) {
        throw 'The VUI Plus isolation profile has the wrong UI stack.'
    }

    Write-Host 'Phase 1 profile setup tests passed.'
} finally {
    $resolvedTemp = [IO.Path]::GetFullPath($tempRoot)
    $systemTemp = [IO.Path]::GetFullPath([IO.Path]::GetTempPath())
    if ($resolvedTemp.StartsWith($systemTemp, [StringComparison]::OrdinalIgnoreCase) -and
        (Test-Path -LiteralPath $resolvedTemp)) {
        Remove-Item -LiteralPath $resolvedTemp -Recurse -Force
    }
}
