[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ProfileScript,
    [Parameter(Mandatory)][string]$FixturePath
)

$ErrorActionPreference = 'Stop'
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ("pbvp-phase2-profile-" + [guid]::NewGuid())
try {
    $profiles = Join-Path $temporaryRoot 'profiles'
    $mods = Join-Path $temporaryRoot 'mods'
    $source = Join-Path $profiles 'Source Profile'
    [IO.Directory]::CreateDirectory($source) | Out-Null
    [IO.Directory]::CreateDirectory($mods) | Out-Null
    [IO.File]::WriteAllLines(
        (Join-Path $source 'modlist.txt'),
        @(
            '# This file was automatically generated by Mod Organizer.',
            '-Pip-Boy Video Player - Dev',
            '+Unrelated Mod'
        ),
        [Text.UTF8Encoding]::new($false))
    [IO.File]::WriteAllText(
        (Join-Path $source 'falloutprefs.ini'),
        "[Display]`nbFull Screen=0`n",
        [Text.UTF8Encoding]::new($false))
    [IO.File]::WriteAllText(
        (Join-Path $temporaryRoot 'ModOrganizer.ini'),
        "selected_profile=@ByteArray(Source Profile)`n",
        [Text.UTF8Encoding]::new($false))
    foreach ($modName in @(
            'Pip-Boy Video Player - Phase 1 Save Guard',
            'Pip-Boy Video Player - Dev')) {
        [IO.Directory]::CreateDirectory((Join-Path $mods $modName)) | Out-Null
    }
    $sourceModListHash = (Get-FileHash -LiteralPath (Join-Path $source 'modlist.txt') -Algorithm SHA256).Hash

    & $ProfileScript `
        -InstanceRoot $temporaryRoot `
        -SourceProfile 'Source Profile' `
        -TargetProfile 'Phase 2 Test' `
        -FixturePath $FixturePath `
        -SelectProfile

    & $ProfileScript `
        -InstanceRoot $temporaryRoot `
        -SourceProfile 'Source Profile' `
        -TargetProfile 'Phase 2 Test' `
        -FixturePath $FixturePath `
        -VerifyOnly

    if ((Get-FileHash -LiteralPath (Join-Path $source 'modlist.txt') -Algorithm SHA256).Hash -cne
        $sourceModListHash) {
        throw 'The source profile changed.'
    }
    $selected = [IO.File]::ReadAllText((Join-Path $temporaryRoot 'ModOrganizer.ini'))
    if ($selected -notmatch '(?m)^selected_profile=@ByteArray\(Phase 2 Test\)$') {
        throw 'The isolated profile was not selected.'
    }
    $targetLines = @(Get-Content -LiteralPath (Join-Path $profiles 'Phase 2 Test\modlist.txt'))
    if (@($targetLines | Where-Object { $_ -eq '+Unrelated Mod' }).Count -ne 1) {
        throw 'The copied profile lost an unrelated mod.'
    }
    if (@(Get-ChildItem -LiteralPath (Join-Path $profiles 'Phase 2 Test\saves') -Force).Count -ne 0) {
        throw 'The isolated profile contains saves.'
    }
    Write-Host 'Phase 2 media profile tests passed.'
} finally {
    if (Test-Path -LiteralPath $temporaryRoot) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
    }
}
