[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ProfileScript,
    [Parameter(Mandatory)][string]$FixturePath
)

$ErrorActionPreference = 'Stop'
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ("pbvp-phase3-profile-" + [guid]::NewGuid())
$profiles = Join-Path $temporaryRoot 'profiles'
$source = Join-Path $profiles 'Source'
$mods = Join-Path $temporaryRoot 'mods'
[IO.Directory]::CreateDirectory((Join-Path $source 'saves')) | Out-Null
[IO.Directory]::CreateDirectory($mods) | Out-Null
[IO.File]::WriteAllLines(
    (Join-Path $source 'modlist.txt'),
    @(
        '# This file was automatically generated by Mod Organizer.',
        '+Existing Mod'
    ),
    [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText(
    (Join-Path $temporaryRoot 'ModOrganizer.ini'),
    "selected_profile=@ByteArray(Source)`n",
    [Text.UTF8Encoding]::new($false))

try {
    & $ProfileScript `
        -InstanceRoot $temporaryRoot `
        -SourceProfile 'Source' `
        -TargetProfile 'Audio Test' `
        -FixturePath $FixturePath `
        -SelectProfile
    & $ProfileScript `
        -InstanceRoot $temporaryRoot `
        -SourceProfile 'Source' `
        -TargetProfile 'Audio Test' `
        -FixturePath $FixturePath `
        -VerifyOnly

    $target = Join-Path $profiles 'Audio Test'
    $modList = @(Get-Content -LiteralPath (Join-Path $target 'modlist.txt'))
    foreach ($required in @(
            '+Pip-Boy Video Player - Phase 1 Save Guard',
            '+Pip-Boy Video Player - Dev',
            '+Pip-Boy Video Player - Audio Test')) {
        if (@($modList | Where-Object { $_ -eq $required }).Count -ne 1) {
            throw "The generated profile is missing: $required"
        }
    }
    $audio = Join-Path $mods 'Pip-Boy Video Player - Audio Test\NVSE\Plugins\PipBoyVideoPlayer\Videos\PBVP-Phase3-Audio.mp4'
    if ((Get-FileHash -LiteralPath $audio -Algorithm SHA256).Hash -cne
        '6549BA517226F8CB0CFB70F3B87489B58AA6ECCFCAB4DB75F808BD219DA1A068') {
        throw 'The generated profile installed the wrong audio fixture.'
    }
    if ([IO.File]::ReadAllText((Join-Path $temporaryRoot 'ModOrganizer.ini')) -notmatch
        '(?m)^selected_profile=@ByteArray\(Audio Test\)$') {
        throw 'The generated profile was not selected.'
    }

    [IO.File]::WriteAllText(
        (Join-Path $target 'saves\must-remain.fos'),
        'test save',
        [Text.UTF8Encoding]::new($false))
    $refused = $false
    try {
        & $ProfileScript `
            -InstanceRoot $temporaryRoot `
            -SourceProfile 'Source' `
            -TargetProfile 'Audio Test' `
            -FixturePath $FixturePath
    } catch {
        $refused = $true
    }
    if (-not $refused -or -not (Test-Path -LiteralPath (Join-Path $target 'saves\must-remain.fos'))) {
        throw 'The profile script did not preserve and refuse existing save data.'
    }

    Write-Host 'Phase 3 audio profile tests passed.'
} finally {
    if (Test-Path -LiteralPath $temporaryRoot) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
    }
}
