[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ProfileScript
)

$ErrorActionPreference = 'Stop'
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ("pbvp-phase5-ui-" + [guid]::NewGuid())
$profilesRoot = Join-Path $temporaryRoot 'profiles'
$modsRoot = Join-Path $temporaryRoot 'mods'
[IO.Directory]::CreateDirectory($profilesRoot) | Out-Null
[IO.Directory]::CreateDirectory($modsRoot) | Out-Null

$sourceProfiles = @(
    'PBVP Phase 1 Base',
    'PBVP Phase 1 VUI Plus',
    'PBVP Phase 1 Extended No Pip-Boy Tweaks',
    'PBVP Phase 1 Extended'
)
$targetProfiles = @(
    'PBVP Phase 5 Base',
    'PBVP Phase 5 VUI Plus',
    'PBVP Phase 5 Extended No Pip-Boy Tweaks',
    'PBVP Phase 5 Extended'
)
$requiredMods = @(
    'Pip-Boy Video Player - Phase 1 Save Guard',
    'Pip-Boy Video Player - Dev',
    'Pip-Boy Video Player - Catalog Test'
)

try {
    foreach ($profileName in $sourceProfiles) {
        $profile = Join-Path $profilesRoot $profileName
        [IO.Directory]::CreateDirectory((Join-Path $profile 'saves')) | Out-Null
        [IO.File]::WriteAllLines(
            (Join-Path $profile 'modlist.txt'),
            @(
                '# This file was automatically generated by Mod Organizer.',
                "+UI Stack $profileName",
                '+Existing Mod',
                '+Pip-Boy Video Player - Playback Test'
            ),
            [Text.UTF8Encoding]::new($false))
        [IO.File]::WriteAllText(
            (Join-Path $profile 'falloutprefs.ini'),
            '[Display]',
            [Text.UTF8Encoding]::new($false))
    }
    foreach ($modName in $requiredMods) {
        [IO.Directory]::CreateDirectory((Join-Path $modsRoot $modName)) | Out-Null
    }
    $videos = Join-Path $modsRoot (
        'Pip-Boy Video Player - Catalog Test\NVSE\Plugins\PipBoyVideoPlayer\Videos')
    [IO.Directory]::CreateDirectory($videos) | Out-Null
    [IO.File]::WriteAllText(
        (Join-Path $videos 'Fixture.mp4'),
        'generated fixture placeholder',
        [Text.UTF8Encoding]::new($false))
    [IO.File]::WriteAllText(
        (Join-Path $temporaryRoot 'ModOrganizer.ini'),
        "selected_profile=@ByteArray(Source)`n",
        [Text.UTF8Encoding]::new($false))

    $sourceHashes = @{}
    foreach ($profileName in $sourceProfiles) {
        $sourceHashes[$profileName] = (Get-FileHash -LiteralPath (
            Join-Path $profilesRoot "$profileName\modlist.txt") -Algorithm SHA256).Hash
    }

    & $ProfileScript -InstanceRoot $temporaryRoot -CreateMissing `
        -SelectProfile 'PBVP Phase 5 VUI Plus'
    & $ProfileScript -InstanceRoot $temporaryRoot -VerifyOnly

    foreach ($profileName in $sourceProfiles) {
        $currentHash = (Get-FileHash -LiteralPath (
            Join-Path $profilesRoot "$profileName\modlist.txt") -Algorithm SHA256).Hash
        if ($currentHash -cne $sourceHashes[$profileName]) {
            throw "The UI profile script changed its source profile: $profileName"
        }
    }
    foreach ($profileName in $targetProfiles) {
        $profile = Join-Path $profilesRoot $profileName
        $lines = @(Get-Content -LiteralPath (Join-Path $profile 'modlist.txt'))
        foreach ($modName in $requiredMods) {
            if (@($lines | Where-Object { $_ -eq "+$modName" }).Count -ne 1) {
                throw "The generated UI profile is missing: $modName"
            }
        }
        foreach ($modName in @(
                'Pip-Boy Video Player - Playback Test',
                'Pip-Boy Video Player - Long Playback Test',
                'Pip-Boy Video Player - Media Test',
                'Pip-Boy Video Player - Audio Test')) {
            if (@($lines | Where-Object { $_ -eq "-$modName" }).Count -ne 1) {
                throw "The generated UI profile did not disable: $modName"
            }
        }
        if (@(Get-ChildItem -LiteralPath (Join-Path $profile 'saves') -Force).Count -ne 0) {
            throw "The generated UI profile contains save data: $profileName"
        }
    }
    if ([IO.File]::ReadAllText((Join-Path $temporaryRoot 'ModOrganizer.ini')) -notmatch
        '(?m)^selected_profile=@ByteArray\(PBVP Phase 5 VUI Plus\)$') {
        throw 'The requested Phase 5 UI profile was not selected.'
    }

    $blockedSave = Join-Path $profilesRoot 'PBVP Phase 5 Base\saves\must-remain.fos'
    [IO.File]::WriteAllText($blockedSave, 'test save', [Text.UTF8Encoding]::new($false))
    $refused = $false
    try {
        & $ProfileScript -InstanceRoot $temporaryRoot -CreateMissing
    } catch {
        $refused = $true
    }
    if (-not $refused -or -not (Test-Path -LiteralPath $blockedSave -PathType Leaf)) {
        throw 'The UI profile script did not preserve and refuse existing save data.'
    }

    Write-Host 'Phase 5 UI matrix profile tests passed.'
} finally {
    if (Test-Path -LiteralPath $temporaryRoot) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
    }
}
