[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ProfileScript,
    [Parameter(Mandatory)][string]$FixturePath
)

$ErrorActionPreference = 'Stop'
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ("pbvp-phase4-profile-" + [guid]::NewGuid())
$profiles = Join-Path $temporaryRoot 'profiles'
$source = Join-Path $profiles 'Source'
$mods = Join-Path $temporaryRoot 'mods'
[IO.Directory]::CreateDirectory((Join-Path $source 'saves')) | Out-Null
[IO.Directory]::CreateDirectory($mods) | Out-Null
[IO.File]::WriteAllLines(
    (Join-Path $source 'modlist.txt'),
    @('# This file was automatically generated by Mod Organizer.', '+Existing Mod'),
    [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText(
    (Join-Path $temporaryRoot 'ModOrganizer.ini'),
    "selected_profile=@ByteArray(Source)`n",
    [Text.UTF8Encoding]::new($false))

try {
    & $ProfileScript -InstanceRoot $temporaryRoot -SourceProfile 'Source' `
        -TargetProfile 'Playback Test' -FixturePath $FixturePath -SelectProfile
    & $ProfileScript -InstanceRoot $temporaryRoot -SourceProfile 'Source' `
        -TargetProfile 'Playback Test' -FixturePath $FixturePath -VerifyOnly

    $target = Join-Path $profiles 'Playback Test'
    $modList = @(Get-Content -LiteralPath (Join-Path $target 'modlist.txt'))
    foreach ($required in @(
            '+Pip-Boy Video Player - Phase 1 Save Guard',
            '+Pip-Boy Video Player - Dev',
            '+Pip-Boy Video Player - Playback Test')) {
        if (@($modList | Where-Object { $_ -eq $required }).Count -ne 1) {
            throw "The generated profile is missing: $required"
        }
    }
    $fixture = Join-Path $mods 'Pip-Boy Video Player - Playback Test\NVSE\Plugins\PipBoyVideoPlayer\Videos\PBVP-Phase4-Playback.mp4'
    if ((Get-FileHash -LiteralPath $fixture -Algorithm SHA256).Hash -cne
        '6549BA517226F8CB0CFB70F3B87489B58AA6ECCFCAB4DB75F808BD219DA1A068') {
        throw 'The generated profile installed the wrong playback fixture.'
    }
    if ([IO.File]::ReadAllText((Join-Path $temporaryRoot 'ModOrganizer.ini')) -notmatch
        '(?m)^selected_profile=@ByteArray\(Playback Test\)$') {
        throw 'The generated profile was not selected.'
    }

    [IO.File]::WriteAllText(
        (Join-Path $target 'saves\must-remain.fos'), 'test save',
        [Text.UTF8Encoding]::new($false))
    $refused = $false
    try {
        & $ProfileScript -InstanceRoot $temporaryRoot -SourceProfile 'Source' `
            -TargetProfile 'Playback Test' -FixturePath $FixturePath
    } catch {
        $refused = $true
    }
    if (-not $refused -or
        -not (Test-Path -LiteralPath (Join-Path $target 'saves\must-remain.fos'))) {
        throw 'The profile script did not preserve and refuse existing save data.'
    }
    Write-Host 'Phase 4 playback profile tests passed.'
} finally {
    if (Test-Path -LiteralPath $temporaryRoot) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
    }
}
