[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$SetupScript
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) (
    "pbvp-gameplay-profile-$([Guid]::NewGuid().ToString('N'))")
$profiles = Join-Path $temporaryRoot 'profiles'
$source = Join-Path $profiles 'Source'
$mods = Join-Path $temporaryRoot 'mods'
[IO.Directory]::CreateDirectory((Join-Path $source 'saves')) | Out-Null
[IO.Directory]::CreateDirectory($mods) | Out-Null

$developmentMods = @(
    'Pip-Boy Video Player - Phase 1 Save Guard',
    'Pip-Boy Video Player - Dev',
    'Pip-Boy Video Player - Catalog Test',
    'Pip-Boy Video Player - Long Playback Test',
    'Pip-Boy Video Player - Fault Test',
    'Pip-Boy Video Player - Playback Test',
    'Pip-Boy Video Player - Media Test',
    'Pip-Boy Video Player - Audio Test')
foreach ($modName in $developmentMods) {
    [IO.Directory]::CreateDirectory((Join-Path $mods $modName)) | Out-Null
}
[IO.File]::WriteAllLines(
    (Join-Path $source 'modlist.txt'),
    @(
        '# This file was automatically generated by Mod Organizer.',
        '+Existing Mod',
        '+Pip-Boy Video Player - Dev',
        '-Pip-Boy Video Player - Audio Test'),
    [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText(
    (Join-Path $source 'fallout.ini'),
    '[Display]',
    [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText(
    (Join-Path $source 'ignored.2026_08_11_12_00_00'),
    'backup',
    [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText(
    (Join-Path $temporaryRoot 'ModOrganizer.ini'),
    "selected_profile=@ByteArray(Source)`n",
    [Text.UTF8Encoding]::new($false))

function New-RuntimeArchive {
    param(
        [Parameter(Mandatory)][string]$Path,
        [switch]$Traversal
    )

    $tree = Join-Path $temporaryRoot "archive-$([Guid]::NewGuid().ToString('N'))"
    [IO.Directory]::CreateDirectory($tree) | Out-Null
    try {
        $files = @(
            'Config/PipBoyVideoPlayer.ini',
            'menus/prefabs/PipBoyVideoPlayer/Player.xml',
            'NVSE/Plugins/PipBoyVideoPlayer.dll',
            'NVSE/Plugins/PipBoyVideoPlayer/bin/avcodec-62.dll',
            'NVSE/Plugins/PipBoyVideoPlayer/bin/avformat-62.dll',
            'NVSE/Plugins/PipBoyVideoPlayer/bin/avutil-60.dll',
            'NVSE/Plugins/PipBoyVideoPlayer/bin/swresample-6.dll',
            'NVSE/Plugins/PipBoyVideoPlayer/bin/swscale-9.dll',
            'uio/public/PipBoyVideoPlayer.txt')
        foreach ($relative in $files) {
            $target = Join-Path $tree $relative
            [IO.Directory]::CreateDirectory((Split-Path -Parent $target)) | Out-Null
            [IO.File]::WriteAllText($target, "fixture $relative")
        }
        [IO.Compression.ZipFile]::CreateFromDirectory($tree, $Path)
        if ($Traversal) {
            $archive = [IO.Compression.ZipFile]::Open(
                $Path,
                [IO.Compression.ZipArchiveMode]::Update)
            try {
                $entry = $archive.CreateEntry('../escaped.txt')
                $writer = [IO.StreamWriter]::new($entry.Open())
                try { $writer.Write('escape') } finally { $writer.Dispose() }
            } finally {
                $archive.Dispose()
            }
        }
    } finally {
        if ((Test-Path -LiteralPath $tree) -and
            [IO.Path]::GetFileName($tree) -like 'archive-*' -and
            (Split-Path -Parent $tree) -eq $temporaryRoot) {
            Remove-Item -LiteralPath $tree -Recurse -Force
        }
    }
}

try {
    $runtimeArchive = Join-Path $temporaryRoot 'runtime.zip'
    New-RuntimeArchive -Path $runtimeArchive
    & $SetupScript `
        -InstanceRoot $temporaryRoot `
        -RuntimeArchive $runtimeArchive `
        -SourceProfile 'Source' `
        -TargetProfile 'Playing' `
        -SelectProfile
    & $SetupScript `
        -InstanceRoot $temporaryRoot `
        -RuntimeArchive $runtimeArchive `
        -SourceProfile 'Source' `
        -TargetProfile 'Playing' `
        -VerifyOnly

    $target = Join-Path $profiles 'Playing'
    $modList = @(Get-Content -LiteralPath (Join-Path $target 'modlist.txt'))
    foreach ($modName in @('Pip-Boy Video Player', 'Pip-Boy Videos')) {
        if (@($modList | Where-Object { $_ -eq "+$modName" }).Count -ne 1) {
            throw "The gameplay profile did not enable: $modName"
        }
    }
    foreach ($modName in $developmentMods) {
        if (@($modList | Where-Object { $_ -eq "-$modName" }).Count -ne 1) {
            throw "The gameplay profile did not disable: $modName"
        }
    }
    if (@($modList | Where-Object { $_ -eq '+Existing Mod' }).Count -ne 1 -or
        -not (Test-Path -LiteralPath (Join-Path $target 'fallout.ini')) -or
        (Test-Path -LiteralPath (Join-Path $target 'ignored.2026_08_11_12_00_00'))) {
        throw 'The gameplay profile did not preserve the intended source configuration.'
    }
    if ([IO.File]::ReadAllText((Join-Path $temporaryRoot 'ModOrganizer.ini')) -notmatch
        '(?m)^selected_profile=@ByteArray\(Playing\)$') {
        throw 'The gameplay profile was not selected.'
    }

    $videoDirectory = Join-Path $mods 'Pip-Boy Videos\NVSE\Plugins\PipBoyVideoPlayer\Videos'
    $personalVideo = Join-Path $videoDirectory 'personal.mp4'
    [IO.File]::WriteAllText($personalVideo, 'personal video sentinel')
    $save = Join-Path $target 'saves\must-remain.fos'
    [IO.File]::WriteAllText($save, 'save sentinel')
    $config = Join-Path $mods 'Pip-Boy Video Player\Config\PipBoyVideoPlayer.ini'
    [IO.File]::WriteAllText($config, 'user config sentinel')

    & $SetupScript `
        -InstanceRoot $temporaryRoot `
        -RuntimeArchive $runtimeArchive `
        -SourceProfile 'Source' `
        -TargetProfile 'Playing'
    if ([IO.File]::ReadAllText($personalVideo) -cne 'personal video sentinel' -or
        [IO.File]::ReadAllText($save) -cne 'save sentinel' -or
        [IO.File]::ReadAllText($config) -cne 'user config sentinel') {
        throw 'A repeat setup changed personal media, save data, or the installed configuration.'
    }

    $unsafeArchive = Join-Path $temporaryRoot 'unsafe.zip'
    New-RuntimeArchive -Path $unsafeArchive -Traversal
    $rejected = $false
    try {
        & $SetupScript `
            -InstanceRoot $temporaryRoot `
            -RuntimeArchive $unsafeArchive `
            -SourceProfile 'Source' `
            -TargetProfile 'Unsafe'
    } catch {
        $rejected = $true
    }
    if (-not $rejected -or (Test-Path -LiteralPath (Join-Path $temporaryRoot 'escaped.txt'))) {
        throw 'The gameplay setup accepted an unsafe archive.'
    }

    Write-Host 'Gameplay profile tests passed.'
} finally {
    if ((Test-Path -LiteralPath $temporaryRoot) -and
        [IO.Path]::GetFileName($temporaryRoot) -like 'pbvp-gameplay-profile-*' -and
        (Split-Path -Parent $temporaryRoot) -eq [IO.Path]::GetTempPath().TrimEnd('\')) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
    }
}
