[CmdletBinding()]
param([Parameter(Mandatory)][string]$ProfileScript)

$ErrorActionPreference = 'Stop'
$script = (Resolve-Path -LiteralPath $ProfileScript).Path
$tempRoot = [IO.Path]::GetFullPath(
    [IO.Path]::Combine([IO.Path]::GetTempPath(), "pbvp-profile-test-$([Guid]::NewGuid().ToString('N'))"))
$profiles = Join-Path $tempRoot 'profiles'
[IO.Directory]::CreateDirectory($profiles) | Out-Null

function New-SourceProfile {
    param([Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)][string]$ModList)
    $profile = Join-Path $profiles $Name
    [IO.Directory]::CreateDirectory($profile) | Out-Null
    [IO.File]::WriteAllText((Join-Path $profile 'modlist.txt'), $ModList)
    [IO.File]::WriteAllText((Join-Path $profile 'fallout.ini'), '[General]')
    [IO.File]::WriteAllText((Join-Path $profile 'falloutprefs.ini'), '')
    $saves = Join-Path $profile 'saves'
    [IO.Directory]::CreateDirectory($saves) | Out-Null
    [IO.File]::WriteAllText((Join-Path $saves 'private.fos'), 'fixture')
}

try {
    New-SourceProfile -Name 'Viva New Vegas' -ModList "-Base separator`n+Base Fixes"
    New-SourceProfile -Name 'Viva New Vegas Extended' -ModList (
        "# This file was automatically generated by Mod Organizer.`n" +
        "+Pip-Boy UI Tweaks - INI`n+Pip-Boy UI Tweaks`n" +
        "+Clean Vanilla Hud`n+Vanilla UI Plus (New Vegas)`n+Extended Fixes")
    [IO.File]::WriteAllText(
        (Join-Path $profiles 'Viva New Vegas Extended\falloutprefs.ini'),
        "iSize W=1920`niSize H=1080`nbFull Screen=1")

    & $script -InstanceRoot $tempRoot -Confirm:$false
    & $script -InstanceRoot $tempRoot -VerifyOnly

    foreach ($target in @(
            'PBVP Phase 1 Base',
            'PBVP Phase 1 VUI Plus',
            'PBVP Phase 1 Extended',
            'PBVP Phase 1 Extended No Pip-Boy Tweaks')) {
        if (Test-Path -LiteralPath (Join-Path $profiles "$target\saves")) {
            throw "The setup copied saves into $target."
        }
    }

    $refused = $false
    try {
        & $script -InstanceRoot $tempRoot -Confirm:$false
    } catch {
        if ($_.Exception.Message -notmatch 'Refusing to replace') {
            throw
        }
        $refused = $true
    }
    if (-not $refused) {
        throw 'The setup replaced existing test profiles.'
    }

    $vuiTarget = [IO.Path]::GetFullPath(
        (Join-Path $profiles 'PBVP Phase 1 VUI Plus'))
    if (-not $vuiTarget.StartsWith(
            [IO.Path]::GetFullPath($profiles) + [IO.Path]::DirectorySeparatorChar,
            [StringComparison]::OrdinalIgnoreCase)) {
        throw 'The VUI Plus fixture escaped the temporary profiles directory.'
    }
    Remove-Item -LiteralPath $vuiTarget -Recurse -Force
    & $script -InstanceRoot $tempRoot -CreateMissing -Confirm:$false
    & $script -InstanceRoot $tempRoot -VerifyOnly

    $vuiList = @(Get-Content -LiteralPath (
        Join-Path $profiles 'PBVP Phase 1 VUI Plus\modlist.txt'))
    if ($vuiList -contains '+Clean Vanilla Hud' -or
        $vuiList -contains '+Pip-Boy UI Tweaks' -or
        $vuiList -contains '+Pip-Boy UI Tweaks - INI' -or
        @($vuiList | Where-Object {
            $_ -eq '+Vanilla UI Plus (New Vegas)'
        }).Count -ne 1) {
        throw 'The VUI Plus isolation profile has the wrong UI stack.'
    }

    Write-Host 'Phase 1 profile setup tests passed.'
} finally {
    $resolvedTemp = [IO.Path]::GetFullPath($tempRoot)
    $systemTemp = [IO.Path]::GetFullPath([IO.Path]::GetTempPath())
    if ($resolvedTemp.StartsWith($systemTemp, [StringComparison]::OrdinalIgnoreCase) -and
        (Test-Path -LiteralPath $resolvedTemp)) {
        Remove-Item -LiteralPath $resolvedTemp -Recurse -Force
    }
}
