[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ProfileScript,
    [Parameter(Mandatory)][string]$FixturePath
)

$ErrorActionPreference = 'Stop'
$temporaryRoot = Join-Path ([IO.Path]::GetTempPath()) ("pbvp-phase5-profile-" + [guid]::NewGuid())
$profiles = Join-Path $temporaryRoot 'profiles'
$source = Join-Path $profiles 'Source'
$mods = Join-Path $temporaryRoot 'mods'
[IO.Directory]::CreateDirectory((Join-Path $source 'saves')) | Out-Null
[IO.Directory]::CreateDirectory($mods) | Out-Null
[IO.File]::WriteAllLines(
    (Join-Path $source 'modlist.txt'),
    @('# This file was automatically generated by Mod Organizer.', '+Existing Mod', '+Pip-Boy Video Player - Long Playback Test'),
    [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText(
    (Join-Path $temporaryRoot 'ModOrganizer.ini'),
    "selected_profile=@ByteArray(Source)`n",
    [Text.UTF8Encoding]::new($false))

try {
    & $ProfileScript -InstanceRoot $temporaryRoot -SourceProfile 'Source' `
        -TargetProfile 'Catalog Test' -FixturePath $FixturePath -SelectProfile
    & $ProfileScript -InstanceRoot $temporaryRoot -SourceProfile 'Source' `
        -TargetProfile 'Catalog Test' -FixturePath $FixturePath -VerifyOnly

    $target = Join-Path $profiles 'Catalog Test'
    $modList = @(Get-Content -LiteralPath (Join-Path $target 'modlist.txt'))
    foreach ($required in @(
            '+Pip-Boy Video Player - Phase 1 Save Guard',
            '+Pip-Boy Video Player - Dev',
            '+Pip-Boy Video Player - Catalog Test',
            '-Pip-Boy Video Player - Long Playback Test')) {
        if (@($modList | Where-Object { $_ -eq $required }).Count -ne 1) {
            throw "The generated profile is missing: $required"
        }
    }
    $videos = Join-Path $mods 'Pip-Boy Video Player - Catalog Test\NVSE\Plugins\PipBoyVideoPlayer\Videos'
    $files = @(Get-ChildItem -LiteralPath $videos -File)
    $japaneseName = -join @(
        [char]0x65E5, [char]0x672C, [char]0x8A9E, '.mp4')
    if ($files.Count -ne 10 -or
        @($files | Where-Object { $_.Name -eq 'Episode 10.mp4' }).Count -ne 1 -or
        @($files | Where-Object { $_.Name -eq $japaneseName }).Count -ne 1) {
        throw 'The generated catalog fixture set is incomplete.'
    }
    if ([IO.File]::ReadAllText((Join-Path $temporaryRoot 'ModOrganizer.ini')) -notmatch
        '(?m)^selected_profile=@ByteArray\(Catalog Test\)$') {
        throw 'The generated profile was not selected.'
    }

    [IO.File]::WriteAllText(
        (Join-Path $target 'saves\must-remain.fos'), 'test save',
        [Text.UTF8Encoding]::new($false))
    $refused = $false
    try {
        & $ProfileScript -InstanceRoot $temporaryRoot -SourceProfile 'Source' `
            -TargetProfile 'Catalog Test' -FixturePath $FixturePath
    } catch {
        $refused = $true
    }
    if (-not $refused -or
        -not (Test-Path -LiteralPath (Join-Path $target 'saves\must-remain.fos'))) {
        throw 'The profile script did not preserve and refuse existing save data.'
    }
    Write-Host 'Phase 5 catalog profile tests passed.'
} finally {
    if (Test-Path -LiteralPath $temporaryRoot) {
        Remove-Item -LiteralPath $temporaryRoot -Recurse -Force
    }
}
