[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)][string]$InstanceRoot,
    [switch]$VerifyOnly
)

$ErrorActionPreference = 'Stop'
$instance = (Resolve-Path -LiteralPath $InstanceRoot).Path
$profiles = Join-Path $instance 'profiles'
if (-not (Test-Path -LiteralPath $profiles -PathType Container)) {
    throw 'The selected MO2 instance has no profiles directory.'
}

$specifications = @(
    [pscustomobject]@{
        Source = 'Viva New Vegas'
        Target = 'PBVP Phase 1 Base'
        DisablePipBoyTweaks = $false
        SeedPrefsFromExtended = $true
    },
    [pscustomobject]@{
        Source = 'Viva New Vegas Extended'
        Target = 'PBVP Phase 1 Extended'
        DisablePipBoyTweaks = $false
        SeedPrefsFromExtended = $false
    },
    [pscustomobject]@{
        Source = 'Viva New Vegas Extended'
        Target = 'PBVP Phase 1 Extended No Pip-Boy Tweaks'
        DisablePipBoyTweaks = $true
        SeedPrefsFromExtended = $false
    }
)

function Resolve-ProfileChild {
    param([Parameter(Mandatory)][string]$Name)
    $candidate = [IO.Path]::GetFullPath((Join-Path $profiles $Name))
    if (-not $candidate.StartsWith(
            $profiles + [IO.Path]::DirectorySeparatorChar,
            [StringComparison]::OrdinalIgnoreCase)) {
        throw "Profile path escaped the MO2 profiles directory: $Name"
    }
    return $candidate
}

function Read-ModList {
    param([Parameter(Mandatory)][string]$Path)
    $lines = [Collections.Generic.List[string]]::new()
    foreach ($line in Get-Content -LiteralPath $Path) {
        $lines.Add($line)
    }
    return ,$lines
}

function Write-ModList {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][Collections.Generic.List[string]]$Lines
    )
    [IO.File]::WriteAllLines($Path, $Lines, [Text.UTF8Encoding]::new($false))
}

function Add-DevelopmentMod {
    param([Parameter(Mandatory)][string]$Path)
    $lines = Read-ModList -Path $Path
    if ($lines.Contains('+Pip-Boy Video Player - Dev')) {
        return
    }
    $insertAt = if ($lines.Count -gt 0 -and
        $lines[0] -eq '# This file was automatically generated by Mod Organizer.') { 1 } else { 0 }
    $lines.Insert($insertAt, '# PBVP Phase 1 test profile. Existing VNV profiles remain unchanged.')
    $lines.Insert($insertAt + 1, '+Pip-Boy Video Player - Dev')
    Write-ModList -Path $Path -Lines $lines
}

function Disable-PipBoyTweaks {
    param([Parameter(Mandatory)][string]$Path)
    $lines = Read-ModList -Path $Path
    for ($index = 0; $index -lt $lines.Count; $index++) {
        if ($lines[$index] -eq '+Pip-Boy UI Tweaks' -or
            $lines[$index] -eq '+Pip-Boy UI Tweaks - INI') {
            $lines[$index] = '-' + $lines[$index].Substring(1)
        }
    }
    Write-ModList -Path $Path -Lines $lines
}

function Test-Profile {
    param([Parameter(Mandatory)]$Specification)
    $target = Resolve-ProfileChild -Name $Specification.Target
    if (-not (Test-Path -LiteralPath $target -PathType Container)) {
        throw "Test profile is missing: $($Specification.Target)"
    }
    if (Test-Path -LiteralPath (Join-Path $target 'saves')) {
        throw "Test profile contains a saves directory: $($Specification.Target)"
    }
    $prefs = Join-Path $target 'falloutprefs.ini'
    if (-not (Test-Path -LiteralPath $prefs -PathType Leaf) -or
        (Get-Item -LiteralPath $prefs).Length -eq 0) {
        throw "Test profile has no usable display preferences: $($Specification.Target)"
    }
    $modList = Join-Path $target 'modlist.txt'
    $lines = @(Get-Content -LiteralPath $modList)
    if (@($lines | Where-Object { $_ -eq '+Pip-Boy Video Player - Dev' }).Count -ne 1) {
        throw "Development mod is not enabled exactly once: $($Specification.Target)"
    }
    if ($Specification.DisablePipBoyTweaks -and
        @($lines | Where-Object {
            $_ -eq '+Pip-Boy UI Tweaks' -or $_ -eq '+Pip-Boy UI Tweaks - INI'
        }).Count -ne 0) {
        throw 'Pip-Boy UI Tweaks remains enabled in its isolation profile.'
    }
}

if (-not $VerifyOnly) {
    foreach ($specification in $specifications) {
        $source = Resolve-ProfileChild -Name $specification.Source
        $target = Resolve-ProfileChild -Name $specification.Target
        if (-not (Test-Path -LiteralPath $source -PathType Container)) {
            throw "Source profile is missing: $($specification.Source)"
        }
        if (Test-Path -LiteralPath $target) {
            throw "Refusing to replace an existing test profile: $($specification.Target)"
        }
        if (-not $PSCmdlet.ShouldProcess($target, "Create $($specification.Target) without saves")) {
            return
        }

        [IO.Directory]::CreateDirectory($target) | Out-Null
        Get-ChildItem -LiteralPath $source -File | Where-Object {
            $_.Name -notmatch '\.\d{4}_\d{2}_\d{2}_'
        } | Copy-Item -Destination $target

        if ($specification.SeedPrefsFromExtended) {
            $extendedPrefs = Join-Path (
                Resolve-ProfileChild -Name 'Viva New Vegas Extended') 'falloutprefs.ini'
            if (-not (Test-Path -LiteralPath $extendedPrefs -PathType Leaf) -or
                (Get-Item -LiteralPath $extendedPrefs).Length -eq 0) {
                throw 'The Extended profile has no display preferences to seed the base test profile.'
            }
            Copy-Item -LiteralPath $extendedPrefs -Destination (
                Join-Path $target 'falloutprefs.ini') -Force
        }

        $modList = Join-Path $target 'modlist.txt'
        Add-DevelopmentMod -Path $modList
        if ($specification.DisablePipBoyTweaks) {
            Disable-PipBoyTweaks -Path $modList
        }
    }
}

foreach ($specification in $specifications) {
    Test-Profile -Specification $specification
}
Write-Host 'Phase 1 MO2 test profiles passed verification.'
