[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)][string]$InstanceRoot,
    [switch]$CreateMissing,
    [switch]$VerifyOnly,
    [ValidateSet(
        'PBVP Phase 5 Base',
        'PBVP Phase 5 VUI Plus',
        'PBVP Phase 5 Extended No Pip-Boy Tweaks',
        'PBVP Phase 5 Extended')]
    [string]$SelectProfile
)

$ErrorActionPreference = 'Stop'
if ($VerifyOnly -and ($CreateMissing -or -not [string]::IsNullOrWhiteSpace($SelectProfile))) {
    throw 'VerifyOnly cannot create or select a profile.'
}

$instance = (Resolve-Path -LiteralPath $InstanceRoot).Path
$profilesRoot = Join-Path $instance 'profiles'
$modsRoot = Join-Path $instance 'mods'
$organizerIni = Join-Path $instance 'ModOrganizer.ini'
foreach ($required in @($profilesRoot, $modsRoot)) {
    if (-not (Test-Path -LiteralPath $required -PathType Container)) {
        throw "The selected MO2 instance is missing a required directory: $required"
    }
}

function Resolve-ChildPath {
    param(
        [Parameter(Mandatory)][string]$Root,
        [Parameter(Mandatory)][string]$Name
    )
    $rootPath = [IO.Path]::GetFullPath($Root).TrimEnd([IO.Path]::DirectorySeparatorChar)
    $candidate = [IO.Path]::GetFullPath((Join-Path $rootPath $Name))
    if (-not $candidate.StartsWith(
            $rootPath + [IO.Path]::DirectorySeparatorChar,
            [StringComparison]::OrdinalIgnoreCase)) {
        throw "Resolved path escaped its expected root: $Name"
    }
    return $candidate
}

function Test-InstanceProcessRunning {
    if (Get-Process -Name 'FalloutNV' -ErrorAction SilentlyContinue) {
        return $true
    }
    foreach ($process in Get-Process -Name 'ModOrganizer' -ErrorAction SilentlyContinue) {
        try {
            if (-not [string]::IsNullOrWhiteSpace($process.Path) -and
                [IO.Path]::GetFullPath((Split-Path -Parent $process.Path)).TrimEnd(
                    [IO.Path]::DirectorySeparatorChar) -ieq $instance.TrimEnd(
                    [IO.Path]::DirectorySeparatorChar)) {
                return $true
            }
        } catch {
            continue
        }
    }
    return $false
}

if (-not $VerifyOnly -and (Test-InstanceProcessRunning)) {
    throw 'Close FalloutNV and Mod Organizer before preparing or selecting a Phase 5 UI profile.'
}

$requiredMods = @(
    'Pip-Boy Video Player - Phase 1 Save Guard',
    'Pip-Boy Video Player - Dev',
    'Pip-Boy Video Player - Catalog Test'
)
foreach ($modName in $requiredMods) {
    $modPath = Resolve-ChildPath -Root $modsRoot -Name $modName
    if (-not (Test-Path -LiteralPath $modPath -PathType Container)) {
        throw "The Phase 5 UI matrix requires the installed test mod: $modName"
    }
}
$catalogVideoRoot = Join-Path (
    Resolve-ChildPath -Root $modsRoot -Name 'Pip-Boy Video Player - Catalog Test') (
    'NVSE\Plugins\PipBoyVideoPlayer\Videos')
if (-not (Test-Path -LiteralPath $catalogVideoRoot -PathType Container) -or
    @(Get-ChildItem -LiteralPath $catalogVideoRoot -File -Filter '*.mp4').Count -eq 0) {
    throw 'The Phase 5 catalog test mod has no MP4 fixtures.'
}

$specifications = @(
    [pscustomobject]@{
        Source = 'PBVP Phase 1 Base'
        Target = 'PBVP Phase 5 Base'
    },
    [pscustomobject]@{
        Source = 'PBVP Phase 1 VUI Plus'
        Target = 'PBVP Phase 5 VUI Plus'
    },
    [pscustomobject]@{
        Source = 'PBVP Phase 1 Extended No Pip-Boy Tweaks'
        Target = 'PBVP Phase 5 Extended No Pip-Boy Tweaks'
    },
    [pscustomobject]@{
        Source = 'PBVP Phase 1 Extended'
        Target = 'PBVP Phase 5 Extended'
    }
)
$disabledTestMods = @(
    'Pip-Boy Video Player - Playback Test',
    'Pip-Boy Video Player - Long Playback Test',
    'Pip-Boy Video Player - Media Test',
    'Pip-Boy Video Player - Audio Test'
)

function Set-TestModState {
    param([Parameter(Mandatory)][string]$ModListPath)
    $lines = [Collections.Generic.List[string]]::new()
    foreach ($line in Get-Content -LiteralPath $ModListPath) {
        $lines.Add($line)
    }
    $comment = '# PBVP Phase 5 UI test profile. Existing VNV profiles remain unchanged.'
    $insertAt = if ($lines.Count -gt 0 -and
        $lines[0] -eq '# This file was automatically generated by Mod Organizer.') { 1 } else { 0 }
    if (-not $lines.Contains($comment)) {
        $lines.Insert($insertAt, $comment)
        $insertAt++
    }
    foreach ($modName in @($requiredMods + $disabledTestMods)) {
        for ($index = $lines.Count - 1; $index -ge 0; $index--) {
            if ($lines[$index] -eq "+$modName" -or $lines[$index] -eq "-$modName") {
                $lines.RemoveAt($index)
            }
        }
    }
    foreach ($modName in $requiredMods) {
        $lines.Insert($insertAt, "+$modName")
        $insertAt++
    }
    foreach ($modName in $disabledTestMods) {
        $lines.Insert($insertAt, "-$modName")
        $insertAt++
    }
    [IO.File]::WriteAllLines($ModListPath, $lines, [Text.UTF8Encoding]::new($false))
}

function Test-Profile {
    param([Parameter(Mandatory)]$Specification)
    $target = Resolve-ChildPath -Root $profilesRoot -Name $Specification.Target
    if (-not (Test-Path -LiteralPath $target -PathType Container)) {
        throw "The Phase 5 UI profile is missing: $($Specification.Target)"
    }
    $saves = Join-Path $target 'saves'
    if ((Test-Path -LiteralPath $saves -PathType Container) -and
        @(Get-ChildItem -LiteralPath $saves -Force).Count -ne 0) {
        throw "The Phase 5 UI profile contains save data: $($Specification.Target)"
    }
    $modListPath = Join-Path $target 'modlist.txt'
    if (-not (Test-Path -LiteralPath $modListPath -PathType Leaf)) {
        throw "The Phase 5 UI profile has no modlist: $($Specification.Target)"
    }
    $lines = @(Get-Content -LiteralPath $modListPath)
    foreach ($modName in $requiredMods) {
        if (@($lines | Where-Object { $_ -eq "+$modName" }).Count -ne 1 -or
            @($lines | Where-Object { $_ -eq "-$modName" }).Count -ne 0) {
            throw "The Phase 5 UI profile does not enable exactly one copy of: $modName"
        }
    }
    foreach ($modName in $disabledTestMods) {
        if (@($lines | Where-Object { $_ -eq "-$modName" }).Count -ne 1 -or
            @($lines | Where-Object { $_ -eq "+$modName" }).Count -ne 0) {
            throw "The Phase 5 UI profile does not disable exactly one copy of: $modName"
        }
    }
}

foreach ($specification in $specifications) {
    $source = Resolve-ChildPath -Root $profilesRoot -Name $specification.Source
    $target = Resolve-ChildPath -Root $profilesRoot -Name $specification.Target
    if (-not (Test-Path -LiteralPath $source -PathType Container)) {
        throw "The isolated Phase 1 source profile is missing: $($specification.Source)"
    }
    if (-not (Test-Path -LiteralPath $target)) {
        if (-not $CreateMissing) {
            throw "The Phase 5 UI profile is missing: $($specification.Target)"
        }
        if (-not $PSCmdlet.ShouldProcess($target, "Create $($specification.Target) without saves")) {
            return
        }
        [IO.Directory]::CreateDirectory($target) | Out-Null
        Get-ChildItem -LiteralPath $source -File | Where-Object {
            $_.Name -notmatch '\.\d{4}_\d{2}_\d{2}_'
        } | Copy-Item -Destination $target
        [IO.Directory]::CreateDirectory((Join-Path $target 'saves')) | Out-Null
        $modListPath = Join-Path $target 'modlist.txt'
        if (-not (Test-Path -LiteralPath $modListPath -PathType Leaf)) {
            throw "The isolated source profile has no modlist: $($specification.Source)"
        }
        Set-TestModState -ModListPath $modListPath
    }
    Test-Profile -Specification $specification
}

if (-not [string]::IsNullOrWhiteSpace($SelectProfile)) {
    if (-not (Test-Path -LiteralPath $organizerIni -PathType Leaf)) {
        throw 'ModOrganizer.ini is missing, so the Phase 5 UI profile cannot be selected.'
    }
    $ini = [IO.File]::ReadAllText($organizerIni)
    if ($ini -notmatch '(?m)^selected_profile=.*$') {
        throw 'ModOrganizer.ini has no selected_profile setting.'
    }
    if ($PSCmdlet.ShouldProcess($organizerIni, "Select $SelectProfile")) {
        $ini = [Text.RegularExpressions.Regex]::Replace(
            $ini,
            '(?m)^selected_profile=.*$',
            "selected_profile=@ByteArray($SelectProfile)",
            1)
        [IO.File]::WriteAllText($organizerIni, $ini, [Text.UTF8Encoding]::new($false))
    }
    if ([IO.File]::ReadAllText($organizerIni) -notmatch
        "(?m)^selected_profile=@ByteArray\($([Text.RegularExpressions.Regex]::Escape($SelectProfile))\)$") {
        throw 'The Phase 5 UI profile selection failed verification.'
    }
}

Write-Host 'Phase 5 UI matrix profiles passed verification.'
